/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.BorderLayout;
import monte_carlo.SCMC;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.IntervalXYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Jožko
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    XYSeries avgSeries, avgSeries2;
    int pocetRep;
    SCMC carlo;

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPoceRep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        tabPanel = new javax.swing.JTabbedPane();
        panelLive = new javax.swing.JPanel();
        panelHistogram = new javax.swing.JPanel();
        panelKrivka = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtZahod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPoceRep.setText("10000000");

        jLabel1.setText("Počet replikacii");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        tabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPanelMouseClicked(evt);
            }
        });

        panelLive.setBackground(new java.awt.Color(102, 102, 102));
        panelLive.setLayout(new java.awt.BorderLayout());
        tabPanel.addTab("Live", panelLive);

        panelHistogram.setBackground(new java.awt.Color(102, 102, 102));
        panelHistogram.setLayout(new java.awt.BorderLayout());
        tabPanel.addTab("Histogram", panelHistogram);

        panelKrivka.setBackground(new java.awt.Color(102, 102, 102));
        panelKrivka.setLayout(new java.awt.BorderLayout());
        tabPanel.addTab("Krivka", panelKrivka);

        jLabel2.setText("Zahodiť prvých");

        txtZahod.setText("10000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtZahod, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPoceRep, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPoceRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtZahod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        pocetRep = Integer.parseInt(txtPoceRep.getText().toString());
        int zahod = Integer.parseInt(txtZahod.getText().toString());
        carlo = new SCMC(pocetRep, zahod);
        avgSeries = new XYSeries("AVG");
        XYSeriesCollection dataset = new XYSeriesCollection(avgSeries);

//        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        JFreeChart lineChart = ChartFactory.createXYLineChart(null, null, null, dataset);
        final NumberAxis rangeAxis = (NumberAxis) lineChart.getXYPlot().getRangeAxis();
        rangeAxis.setAutoRangeIncludesZero(false);
        ChartPanel chartPanel = new ChartPanel(lineChart);

        panelLive.removeAll();
        panelLive.add(chartPanel, BorderLayout.CENTER);
        panelLive.validate();
//        dataset.addValue(33, "", "test 3");
        carlo.simuluj(avgSeries, pocetRep);

    }//GEN-LAST:event_btnStartActionPerformed

    private void tabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPanelMouseClicked
        // TODO add your handling code here:
       
        
        switch (tabPanel.getSelectedIndex()) {

            case 1:
                createHistogram();
                break;
            case 2:
                System.out.println("--------------------------******************************");
                createKrivka();
                break;
        }


    }//GEN-LAST:event_tabPanelMouseClicked

    private void createHistogram() {
        IntervalXYDataset dataset = carlo.getDataset();
        JFreeChart chart = ChartFactory.createHistogram("Histogram", "Pocet dni", "Pocet", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel myChart = new ChartPanel(chart);
        myChart.setMouseWheelEnabled(true);
        panelHistogram.setLayout(new java.awt.BorderLayout());
        panelHistogram.add(myChart, BorderLayout.CENTER);
        panelHistogram.validate();
    }

    public void createKrivka() {
        System.out.println("sommmmm");
        XYSeriesCollection dataset = carlo.getDataSetKrivka();
//        carlo.otazkaDva();
//        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        JFreeChart lineChart = ChartFactory.createXYLineChart(null, null, null, dataset);
        final NumberAxis rangeAxis = (NumberAxis) lineChart.getXYPlot().getRangeAxis();
        rangeAxis.setAutoRangeIncludesZero(false);
        ChartPanel chartPanel = new ChartPanel(lineChart);

        panelKrivka.setLayout(new java.awt.BorderLayout());
        panelKrivka.add(chartPanel, BorderLayout.CENTER);
        panelKrivka.validate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JPanel panelHistogram;
    private javax.swing.JPanel panelKrivka;
    private javax.swing.JPanel panelLive;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTextField txtPoceRep;
    private javax.swing.JTextField txtZahod;
    // End of variables declaration//GEN-END:variables
}
